#
#
#
# UPDATE deplay: repo & $NPM settings
#
#
#
#


sudo: false
language: node_js
node_js:
  - node
branches:
  only:
  - master
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - npm version patch -m "Bumping to %s"
deploy:
  skip_cleanup: true
  provider: npm
  #email: $NPM_USER
  #api_key: $NPM_TOKEN
  on:
    #repo: *********************************
    branch: master
notifications:
  email: false
